### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by meroluo** [MIVRC/MSRN-PyTorch#9]
hello, I want to train the model with my own dataset, but meet some problems in the training. The problem described as below:
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/dataloader.py", line 47, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/dataloader.py", line 47, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/data/srdata.py", line 148, in __getitem__
    lr, hr = self.get_patch(lr, hr)
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/data/srdata.py", line 197, in get_patch
    multi_scale=multi_scale
  File "/home/weihq/superresolution1/MSRN-PyTorch-master/MSRN-PyTorch-master/MSRN/Train/data/common.py", line 21, in get_patch
    args[0][iy:iy + ip, ix:ix + ip, :],
IndexError: too many indices for array

I don't know what's happened in the process, is the size of my images too big?

**Comment by CV-JunchengLi** [comment]
Can you provide an example of your dataset format and storage path?

**Comment by CV-JunchengLi** [comment]
I guess this may be because there are single-channel images or multi-channel (more than 3 channels) images in your dataset？

**Comment by meroluo** [comment]
Thank you for your suggestion! I find my dataset contains some images including 1 channel and 3 channel, it may cause this problem. So the dataset can only be colorful images with 3 channel? If I want use 1 channel images, then what can I  do?

**Comment by CV-JunchengLi** [comment]
set n_colors = 1

**Comment by meroluo** [comment]
> set n_colors = 1

Thank you for your help!
 I want to know whether I can only use the dataset containing one type of images such as one channel or three channels. Can't I use  both types of channel as training images in the same time? 
Can you give me some suggestion on how to modify the file to train both 1 channel and 3 channels images in the same time!?  Sincerely grateful!

**Comment by CV-JunchengLi** [comment]
if you use 1 channel images only, you must set n_color = 1
and modify the following code in
https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Train/data/common.py
change
ret = [
        args[0][iy:iy + ip, ix:ix + ip, :],
        *[a[ty:ty + tp, tx:tx + tp, :] for a in args[1:]]
    ]
to
ret = [
        args[0][iy:iy + ip, ix:ix + ip],
        *[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
    ]
-----------------------------------------------------------------

change

def _augment(img):
        if hflip: img = img[:, ::-1, :]
        if vflip: img = img[::-1, :, :]
        if rot90: img = img.transpose(1, 0, 2)

to 
def _augment(img):
        if hflip: img = img[:, ::-1]
        if vflip: img = img[::-1, :]
        #if rot90: img = img.transpose(1, 0, 2)


And if you use the dataset containing one channel and three channels.

I think the code may be can work, because of the set_channel function will set them to the same channel.

def set_channel(*args, n_channels=3):
    def _set_channel(img):
        if img.ndim == 2:
            img = np.expand_dims(img, axis=2)

        c = img.shape[2]
        if n_channels == 1 and c == 3:
            img = np.expand_dims(sc.rgb2ycbcr(img)[:, :, 0], 2)
        elif n_channels == 3 and c == 1:
            img = np.concatenate([img] * n_channels, 2)

        return img

    return [_set_channel(a) for a in args]

But if you don't need this change, I have no idea now.
I never have tried it~ maybe I can tell you when I know it.

**Comment by CV-JunchengLi** [comment]
if you use 1 channel images only, you must set n_color = 1
and modify the following code in
https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Train/data/common.py

change
ret = [
args[0][iy:iy + ip, ix:ix + ip, :],
*[a[ty:ty + tp, tx:tx + tp, :] for a in args[1:]]
]
to
ret = [
args[0][iy:iy + ip, ix:ix + ip],
*[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
]
change

def _augment(img):
if hflip: img = img[:, ::-1, :]
if vflip: img = img[::-1, :, :]
if rot90: img = img.transpose(1, 0, 2)

to
def _augment(img):
if hflip: img = img[:, ::-1]
if vflip: img = img[::-1, :]
#if rot90: img = img.transpose(1, 0, 2)

And if you use the dataset containing one channel and three channels.

I think the code may be can work, because of the set_channel function will set them to the same channel.

def set_channel(*args, n_channels=3):
def _set_channel(img):
if img.ndim == 2:
img = np.expand_dims(img, axis=2)

    c = img.shape[2]
    if n_channels == 1 and c == 3:
        img = np.expand_dims(sc.rgb2ycbcr(img)[:, :, 0], 2)
    elif n_channels == 3 and c == 1:
        img = np.concatenate([img] * n_channels, 2)

    return img

return [_set_channel(a) for a in args]
But if you don't need this change, I have no idea now.
I never have tried it~ maybe I can tell you when I know it.

**Comment by CV-JunchengLi** [comment]
if you use 1 channel images only, you must set n_color = 1
and modify the following code in
https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Train/data/common.py

change
``
ret = [
args[0][iy:iy + ip, ix:ix + ip, :],
*[a[ty:ty + tp, tx:tx + tp, :] for a in args[1:]]
]
``
to
``
ret = [
args[0][iy:iy + ip, ix:ix + ip],
*[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
]


change

def _augment(img):
if hflip: img = img[:, ::-1, :]
if vflip: img = img[::-1, :, :]
if rot90: img = img.transpose(1, 0, 2)

to
def _augment(img):
if hflip: img = img[:, ::-1]
if vflip: img = img[::-1, :]
#if rot90: img = img.transpose(1, 0, 2)

And if you use the dataset containing one channel and three channels.

I think the code may be can work, because of the set_channel function will set them to the same channel.
~~~
def set_channel(*args, n_channels=3):
def _set_channel(img):
if img.ndim == 2:
img = np.expand_dims(img, axis=2)

    c = img.shape[2]
    if n_channels == 1 and c == 3:
        img = np.expand_dims(sc.rgb2ycbcr(img)[:, :, 0], 2)
    elif n_channels == 3 and c == 1:
        img = np.concatenate([img] * n_channels, 2)

    return img

return [_set_channel(a) for a in args]


But if you don't need this change, I have no idea now.
I never have tried it~ maybe I can tell you when I know it.

**Comment by CV-JunchengLi** [comment]
if you use 1 channel images only, you must set n_color = 1
and modify the following code in
https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Train/data/common.py

change
```
ret = [
        args[0][iy:iy + ip, ix:ix + ip, :],
        *[a[ty:ty + tp, tx:tx + tp, :] for a in args[1:]]
    ]
```
to
```
ret = [
        args[0][iy:iy + ip, ix:ix + ip],
        *[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
    ]
```

change

```
    def _augment(img):
        if hflip: img = img[:, ::-1, :]
        if vflip: img = img[::-1, :, :]
        if rot90: img = img.transpose(1, 0, 2)
        
        return img
```

to

```
 def _augment(img):
        if hflip: img = img[:, ::-1]
        if vflip: img = img[::-1, :]
        #if rot90: img = img.transpose(1, 0, 2)
        
        return img
```

And if you use the dataset containing one channel and three channels.

I think the code may be can work, because of the set_channel function will set them to the same channel.

```
def set_channel(*args, n_channels=3):
    def _set_channel(img):
        if img.ndim == 2:
            img = np.expand_dims(img, axis=2)

        c = img.shape[2]
        if n_channels == 1 and c == 3:
            img = np.expand_dims(sc.rgb2ycbcr(img)[:, :, 0], 2)
        elif n_channels == 3 and c == 1:
            img = np.concatenate([img] * n_channels, 2)

        return img

    return [_set_channel(a) for a in args]

```
But if you don't need this change, I have no idea now.
I never have tried it~ maybe I can tell you when I know it.

**Comment by meroluo** [comment]
> if you use 1 channel images only, you must set n_color = 1
> and modify the following code in
> https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Train/data/common.py
> change
> ret = [
>         args[0][iy:iy + ip, ix:ix + ip, :],
>         *[a[ty:ty + tp, tx:tx + tp, :] for a in args[1:]]
>     ]
> 
> to
> ret = [
>         args[0][iy:iy + ip, ix:ix + ip],
>         *[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
>     ]
> 
> change
>     def _augment(img):
>         if hflip: img = img[:, ::-1, :]
>         if vflip: img = img[::-1, :, :]
>         if rot90: img = img.transpose(1, 0, 2)
>         
>         return img
> 
> to
>  def _augment(img):
>         if hflip: img = img[:, ::-1]
>         if vflip: img = img[::-1, :]
>         #if rot90: img = img.transpose(1, 0, 2)
>         
>         return img
> 
> And if you use the dataset containing one channel and three channels.
> I think the code may be can work, because of the set_channel function will set them to the same channel.
> def set_channel(*args, n_channels=3):
>     def _set_channel(img):
>         if img.ndim == 2:
>             img = np.expand_dims(img, axis=2)
> 
>         c = img.shape[2]
>         if n_channels == 1 and c == 3:
>             img = np.expand_dims(sc.rgb2ycbcr(img)[:, :, 0], 2)
>         elif n_channels == 3 and c == 1:
>             img = np.concatenate([img] * n_channels, 2)
> 
>         return img
> 
>     return [_set_channel(a) for a in args]
> 
> 
> But if you don't need this change, I have no idea now.
> I never have tried it~ maybe I can tell you when I know it.

Your suggestions help me a lot! Thank you very much! Now I can train with both 1 channel and 3 channels images.

**Comment by CV-JunchengLi** [comment]
you are welcome
